// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TCEditproduct01Test
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }

    [Test]
    public void TCEditproduct01()
    {
        driver.Navigate().GoToUrl("http://foodfarmvn.somee.com/");
        driver.Manage().Window.Size = new System.Drawing.Size(1050, 708);
        driver.FindElement(By.Id("ucHeaderMain_lbtDangNhap")).Click();
        driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);
        driver.FindElement(By.Id("ContentPlaceHolder1_txtUsername")).Click();
        driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);
        js.ExecuteScript("window.scrollTo(0,200)");
        driver.FindElement(By.Id("ContentPlaceHolder1_txtUsername")).SendKeys("TaiLinh");
        driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);
        driver.FindElement(By.Id("ContentPlaceHolder1_txtPassword")).Click();
        driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);
        driver.FindElement(By.Id("ContentPlaceHolder1_txtPassword")).SendKeys("12345");
        driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);
        driver.FindElement(By.Id("ContentPlaceHolder1_btnSubmit")).Click();
        driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);
        driver.FindElement(By.Id("ContentPlaceHolder1_lbtEditProduct")).Click();
        driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);
        driver.FindElement(By.CssSelector("#ContentPlaceHolder1_gvEdit_hlEdit_0 > .fa")).Click();
        driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);
        driver.FindElement(By.CssSelector("tbody:nth-child(2) > tr:nth-child(1)")).Click();
        driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);
        js.ExecuteScript("window.scrollTo(0,200)");
        driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);
        driver.FindElement(By.Id("ContentPlaceHolder1_gvEditProduct_txtProductName_0")).SendKeys("Jack Fruit");
        driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);
        driver.FindElement(By.Id("ContentPlaceHolder1_gvEditProduct_txtPrice_0")).Click();
        driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);
        driver.FindElement(By.Id("ContentPlaceHolder1_gvEditProduct_txtPrice_0")).SendKeys("2000");
        driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);
        driver.FindElement(By.Id("ContentPlaceHolder1_gvEditProduct_txtUnit_0")).Click();
        driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);
        js.ExecuteScript("window.scrollTo(200,1200)");
        driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);
        driver.FindElement(By.Id("ContentPlaceHolder1_gvEditProduct_BtnSubmit_0")).Click();
    }
}
